spring:
  datasource:
    url: jdbc:mariadb://172.30.1.87:1004/vintly
    driver-class-name: org.mariadb.jdbc.Driver
    username: kyc
    password: kyc1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
